/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "rpc_envelope.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(RpcEnvelope, RpcEnvelope, 2)


PB_BIND(RpcResponse, RpcResponse, 2)



